server:
  port: 8080

spring:
  application:
    name: ewm-main-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

ewm:
  stats:
    base-url: ${STATS_BASE_URL:http://localhost:9090}
    app-name: ewm-main-service

management:
  endpoints.web.exposure.include: health,info,metrics

logging:
  level:
    org.springframework.web: DEBUG
